---

repos:
  ubuntu:
    docker-ce:
      url: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      key: "https://download.docker.com/linux/ubuntu/gpg"
    fluentd:
      url: "deb http://packages.treasuredata.com/2/ubuntu/{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} contrib"
      key: "https://packages.treasuredata.com/GPG-KEY-td-agent"
  redhat:
    docker-ce:
      url: https://download.docker.com/linux/centos/docker-ce.repo

packages:
  ubuntu:
    install:
      - docker-ce
      - td-agent
  redhat:
    install:
      - docker-ce

pip:
  install:
    ansible:
      version: 1.9.1
