---

- name: PIP - install packages
  become: yes
  action:
    module: pip
    executable: "pip{{version | default(2.7)}}"
    name: "{{python['common']['pip']['packages']['install']}}"
    state: latest
