---

- name: "SERVICE - enable mongod service"
  become: yes
  action:
    module: service
    state: started
    name: "{{mongodb[ansible_distribution | lower]['service']['name']}}"
    enabled: yes
  register: service_enable
  notify: "restart_{{ansible_service_mgr}}_mongod"

- name: "MONGODB_USER - Add admin users"
  action:
    module: mongodb_user
    database: admin
    user: "{{item['name']}}" 
    password: "{{item['password']}}" 
    state: present
    roles: "{{item['roles']}}"
  with_items: "{{mongodb['auth']['users']}}"
  when: service_enable.changed

- name: "COPY - Copy replica set key"
  become: yes
  action:
    module: copy 
    dest: "{{mongodb[ansible_distribution | lower]['config']['data']['path']['default']}}/replica.key"
    content: "{{mongodb['config']['replica']['key']['content']}}"
    owner: "{{mongodb['user']}}"
    group: "{{mongodb['group']}}"
    mode: "{{mongodb['config']['replica']['key']['perms']}}" 
  when: mongodb['config']['replica'] is defined

- name: "TEMPLATE - Systemd unit file change"
  become: yes
  action:
    module: template
    src: "{{mongodb['config']['systemd']['unit']['file']}}"
    dest: "{{mongodb['config']['systemd']['unit']['file']}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: systemd_unit_change
  notify: "reload_daemon_mongod"

- name: "TEMPLATE - config file change"
  become: yes
  action:
    module: template
    src: "{{mongodb[ansible_distribution | lower]['config']['file']}}" 
    dest: "{{mongodb[ansible_distribution | lower]['config']['path']}}/{{mongodb[ansible_distribution | lower]['config']['file']}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: "restart_mongod" 

