---

- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - openjdk-9-jre

- name: Add apt key from URL
  apt_key:
    url: "{{elasticsearch[ansible_distribution | lower]['install']['repository']['key']['url']}}" 
    state: present

- name: Add apt repository 
  apt_repository:
    repo: "{{elasticsearch[ansible_distribution | lower]['install']['repository']['url']}}" 
    update_cache: yes
    state: present

- name: Install elsticsearch package
  apt:
    name: elasticsearch 
    state: present
