---

- name: "APT_REPOSITORY - Add external repositories"
  become: yes
  action:
    module: apt_repository
    state: present
    update_cache: yes
    repo: "{{item}}"
  with_items: "{{ruby[ansible_distribution | lower]['repos']}}"

- name: "APT - remove packages"
  become: yes
  action:
    module: apt
    name: "{{item}}"
    state: absent
  with_items: "{{ruby[ansible_distribution | lower]['packages']['remove']}}"

- name: "APT - install packages"
  become: yes
  action:
    module: apt
    name: '{{item}}'
    state: latest
    allow_unauthenticated: yes
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ruby[ansible_distribution | lower]['packages']['install']}}" 
