---

python:
   common:
      pip:
         packages:
            install: 
               - setuptools
               - urllib3
               - pyOpenSSL
               - ndg-httpsclient 
               - pyasn1
   ubuntu:
      packages:
         install: 
            - "python{{version | default(2.7)}}"
            - "python{{version | default(2.7)}}-dev"
            - python-pip
    