---

- name: "FILE - create ssh keys directory"
  become: yes
  action:
    module: file
    path: "{{jenkins['common']['user']['home']}}/{{jenkins['common']['credentials']['keydir']}}" 
    owner: "{{jenkins['common']['user']['name']}}"
    group: "{{jenkins['common']['user']['group']['name']}}"
    state: directory
    mode: 0700 

- name: "FILE - create ssh user key directory"
  become: yes
  action:
    module: file
    path: "{{jenkins['common']['user']['home']}}/{{jenkins['common']['credentials']['keydir']}}/{{item['name']}}"
    owner: "{{jenkins['common']['user']['name']}}"
    group: "{{jenkins['common']['user']['group']['name']}}"
    state: directory
    mode: 0700
  when: item['type'] == "ssh"
  with_items: "{{jenkins['common']['credentials']['users']}}"

- name: "COPY - add ssh user key"
  become: yes
  action:
    module: copy
    src: "keys/{{item['name']}}/id_rsa"
    dest: "{{jenkins['common']['user']['home']}}/{{jenkins['common']['credentials']['keydir']}}/{{item['name']}}/id_rsa" 
    owner: "{{jenkins['common']['user']['name']}}" 
    group: "{{jenkins['common']['user']['group']['name']}}" 
    mode: '0600'
    directory_mode: '0700'
  when: item['type'] == "ssh"
  with_items: "{{jenkins['common']['credentials']['users']}}"

- name: "TEMPLATE - Modify credentials XML"
  become: yes
  action:
    module: template
    src: "{{jenkins['common']['credentials']['file']}}"
    dest: "{{jenkins['common']['user']['home']}}/{{jenkins['common']['credentials']['file']}}"
    owner: "{{jenkins['common']['user']['name']}}"
    group: "{{jenkins['common']['user']['group']['name']}}"
    mode: 0644
    backup: yes
  when: rol == "master"
  notify: restart_jenkins


