---

- name: TEMPLATE - Copy plugins install script
  become: yes
  action:
    module: template
    src: "scripts/{{jenkins['common']['plugins']['script']}}"
    dest: "{{jenkins['common']['user']['home']}}"
    owner: "{{jenkins['common']['user']['name']}}"
    group: "{{jenkins['common']['user']['group']['name']}}"
    mode: 0744
    backup: yes
  when: rol == "master"

- name: SHELL - Install plugins
  become: yes
  shell: "{{jenkins['common']['user']['home']}}/{{jenkins['common']['plugins']['script']}} {{jenkins['common']['plugins']['install'] | join(' ')}}"
  notify: restart_jenkins
