---

- name: TEMPLATE - config file change
  become: yes
  action:
    module: template
    src: "{{es_version | default(5.x)}}/{{elasticsearch[ansible_distribution | lower]['config']['file']}}" 
    dest: "{{elasticsearch[ansible_distribution | lower]['config']['path']}}/{{elasticsearch[ansible_distribution | lower]['config']['file']}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: "restart_elasticsearch" 
