pipeline {
    agent any
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    stages {
        stage('Create python virtualenv'){
            steps{
                sh script: """
                    virtualenv -p /usr/bin/python2.7 .venv
                    source .venv/bin/activate
                    [ -f requirements.txt ] && pip install -r requirements.txt
                """
            }
        }
        stage('Test molecule environment'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'ost-epg-admin', usernameVariable: 'OS_USERNAME', passwordVariable: 'OS_PASSWORD')]) {
                    sh script: """
                        [ -e \$VIRTUALENV ] && source .venv/bin/activate       
                        cd roles/test
                        molecule create
                    """
                }
            }
        }
    }
    post{
        success{
            deleteDir()
        }
    }
}