---

docker:
   common: 
      bin:
         daemon: /usr/bin/dockerd
      systemd:
         unit_file: /lib/systemd/system/docker.service
      crones:
         - name: 'Docker prune'
           user: root
           job: 'docker system prune -af --volumes'
           minute: 0
           hour: 0
           weekday: '*'
           day: '*'
           month: '*'
      config:
         dir: /etc/docker
         daemon:
            file: daemon.json
            options:
               default:
                  debug: false 
                  hosts:
                     - fd://
                  insecure-registries:
               manager:
                  debug: false
                  hosts:
                     - tcp://0.0.0.0:4243
                     - fd://
                  insecure-registries:
               worker:
                  debug: false
                  hosts:
                     - fd://
                  insecure-registries:
   centos:
      service: docker
      repos:
         - name: Docker CE
           repo: https://download.docker.com/linux/centos/docker-ce.repo
      packages:
         - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.12.1.ce-1.el7.centos.x86_64.rpm
         - python-docker-py
   ubuntu:
      service: docker
      default_config: /etc/default/docker
      repos:
         - name: Docker CE
           repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
           key: https://download.docker.com/linux/ubuntu/gpg
      packages:
         - docker-ce

