---

- name: Set timezone
  become: yes
  timezone:
     name: Europe/Madrid

- include_tasks: "{{ ansible_distribution | lower }}/install.yml"
- include_tasks: "{{ ansible_distribution | lower }}/config.yml"
