---

- name: GET_URL - Download package"
  action:
    module: get_url
    url: "{{vagrant['package']['url']['base']}}/{{vagrant['package']['version']}}/vagrant_{{vagrant['package']['version']}}_{{ansible_architecture}}.deb" 
    dest: "/tmp/vagrant_{{vagrant['package']['version']}}_{{ansible_architecture}}.deb"
    validate_certs: no
  register: package_download

- name: APT - Install package
  become: yes
  action:
    module: apt
    deb: "/tmp/vagrant_{{vagrant['package']['version']}}_{{ansible_architecture}}.deb"
  when: package_download.changed
  register: package_install

- name: SHELL - Install plugins
  shell: "vagrant plugin install {{item}}"
  with_items: "{{vagrant['plugins']}}"
  when: package_install.changed
