
PYTHON 	= /usr/bin/python2.7
VENV   	= .venv

default:
	@echo ""
	@echo "Options available"
	@echo "  - venv"
	@echo "  - clean"
	@echo "  - create"
	@echo ""

venv:
	@echo "Creating virtualenv in $(VENV) ..."
	virtualenv -p $(PYTHON) $(VENV);source $(VENV)/bin/activate;
