---

- name: Install required packages 
  yum:
    name: "{{item}}" 
    state: latest
  with_items:
    - java-1.8.0-openjdk-headless

- name: Add repository
  yum_repository:
    name: elasticsearch
    description: Elasticsearch official repository 
    gpgkey: "{{elasticsearch[ansible_distribution | lower]['install']['repository']['key']['url']}}" 
    gpgcheck: true
    baseurl: "{{elasticsearch[ansible_distribution | lower]['install']['repository']['url']}}" 
    

- name: Install elasticsearch 
  yum:
    name: elasticsearch 
    state: latest
    update_cache: yes
