---

- name: APT_REPOSITORY - Add repository
  become: yes
  action:
    module: apt_repository
    state: present
    update_cache: yes
    repo: "{{java[ansible_distribution | lower]['repo']}}"

- name: SHELL - Accept Oracle License
  become: yes
  shell: "echo oracle-java{{java_version | default(8)}}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"
  changed_when: no

- name: APT - install packages
  become: yes
  action:
    module: apt
    name: "{{item}}" 
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{java[ansible_distribution | lower]['packages']['install']}}"
