---

- name: Add external repos
  become: yes
  yum_repository:
    state: present
    name: docker-ce
    description: Docker CE repository
    baseurl: "{{ item.value.url }}"
    gpgcheck: no
  with_dict: "{{ repos[ansible_distribution | lower] }}"

- name: Install required packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages[ansible_distribution | lower].install }}"

